In [ ]:
10 +3

13

In [ ]:
2* 3

6

In [ ]:
x = 12

In [ ]:
x

12

In [ ]:
Y = 15
x + Y

27

In [ ]:
'Hola mundo'

'Hola mundo'

In [ ]:
[1,2,3,4,5] +[2,6,7,8,9,10]

[1, 2, 3, 4, 5, 2, 6, 7, 8, 9, 10]

In [ ]:
lista = [0,1,2,3,4,5,6,7,8,9,10]

In [ ]:
lista[-1]

10

In [10]:
import numpy as np

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [13]:
np.array([1,2,3,4,5]).shape

(5,)

In [14]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.array([[1,2,3,4,5],[6,7,8,9,10]]).shape

(2, 5)

In [16]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])[0]

array([1, 2, 3, 4, 5])

In [17]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])[0][2]

3